/**
 * Utility Module
 * 
 * Shared utility functions for dates, strings, validation, and error handling.
 * 
 * @module lib/utils
 */

// Date Helpers
export {
  parseDate,
  parseDateOrNow,
  parseDateFlexible,
  formatDate,
  formatMedicalDate,
  formatISODate,
  formatDateTime,
  formatTime,
  formatDateForFilename,
  formatRelativeTime,
  calculateAge,
  isAdult,
  daysBetween,
  isPast,
  isFuture,
  isToday,
  addDaysToDate,
  subtractDaysFromDate,
  getStartOfDay,
  getEndOfDay,
  getDayRange,
  validateDateRange,
  isWithinLastDays,
  isWithinNextDays,
  deidentifyDate,
  isValidMedicalDate,
  calculateRetentionDate,
  toTimeZone,
  getCurrentDateInTimeZone,
  createDateInTimeZone,
  DATE_FORMATS,
  DEFAULT_TIMEZONE,
  type DateRange,
  type TimeZoneOptions,
} from './date-helpers';

// String Helpers
export {
  truncate,
  capitalize,
  capitalizeWords,
  toCamelCase,
  toPascalCase,
  toSnakeCase,
  toKebabCase,
  slugify,
  randomString,
  generateId,
  formatPhoneNumber,
  formatSSN,
  formatZipCode,
  formatNumber,
  formatCurrency,
  maskString,
  maskEmail,
  redact,
  isEmpty,
  isNumeric,
  isValidEmail,
  containsAny,
  parseBoolean,
  parseIntSafe,
  parseFloatSafe,
  removeExtraWhitespace,
  removeAllWhitespace,
  removeLineBreaks,
  formatPatientName,
  formatMRN,
  abbreviateMedical,
  type TruncateOptions,
  type SlugifyOptions,
} from './string-helpers';

// Validation Helpers
export {
  validateRequired,
  validateEmail,
  validatePhone,
  validateZipCode,
  validateSSN,
  validateLength,
  validatePattern,
  validateCaliforniaZip,
  validateCaliforniaState,
  validateDateOfBirth,
  validateMRN,
  validateNumberRange,
  validatePositiveNumber,
  validateNonEmptyArray,
  validateArrayLength,
  validateObject,
  validateChain,
  validatePasswordsMatch,
  validateTermsAccepted,
  ValidationRules,
  sanitizeInput,
  normalizeForComparison,
  type ValidationResult,
  type ValidationRule,
  type FieldValidation,
} from './validation-helpers';

// Error Helpers
export {
  AppError,
  AuthError,
  ValidationError,
  HIPAAError,
  NotFoundError,
  RateLimitError,
  DatabaseError,
  isOperationalError,
  isAppError,
  isAuthError,
  isValidationError,
  getErrorStatusCode,
  getSafeErrorMessage,
  formatErrorResponse,
  logError,
  withErrorHandling,
  tryOrDefault,
  tryOrDefaultAsync,
  createErrorResponse,
  assert,
  assertExists,
  ERROR_STATUS_CODES,
  type ErrorCode,
} from './error-helpers';
